<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFtrpgud\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFtrpgud/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFtrpgud.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFtrpgud\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFtrpgud\appProdProjectContainer(array(
    'container.build_hash' => 'Ftrpgud',
    'container.build_id' => '26fdd5ab',
    'container.build_time' => 1538066615,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFtrpgud');
