<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZr0sxs0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZr0sxs0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZr0sxs0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZr0sxs0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZr0sxs0\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zr0sxs0',
    'container.build_id' => 'aee8d9b2',
    'container.build_time' => 1538444825,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZr0sxs0');
